### ISSUE TITLE
Misleading installation instructions

### ISSUE THREAD

**Issue by qexat** [benjaminpmd/vManager#1]
The issue is about this paragraph: https://github.com/benjaminpmd/vManager#installation

`apt` is the package manager for Debian-based Linux distributions (e.g. Ubuntu), but it does not exist on other distros or macOS.

The recommended way for macOS is to use Homebrew:
```
brew install tkinter
```

For the other Linux distributions, I suggest that you write something like "Install Tkinter using your package manager" as there would be too many to cover.

PS: it seems that there is a French version of the README -- if you make a change don't forget to have it reflected :)

**Comment by benjaminpmd** [comment]
Both README have been fixed, thank you for the info and the tips!
